// @generated by ESS 0.50.0; do not edit.
// Source SHA-256: 9ce1d16ddc198a1c3933985d4ae7c2a3b94fe24f56e5626ec84ab681650ef441
// Model schema projection SHA-256: 1027fd8c4a1a06ffbe34e55d32dff3d6ceef2028ee6cb7f18cfc609e1ea2a699
// Structural serialization only; see types-report.json for runtime obligations.

/// Absence is independent of the field value, including a present JSON null.
#[derive(Debug, Clone, PartialEq)]
pub enum EssPresence<T> {
    Absent,
    Present(T),
}

impl<T> Default for EssPresence<T> {
    fn default() -> Self { Self::Absent }
}

impl<T> EssPresence<T> {
    pub fn is_absent(&self) -> bool { matches!(self, Self::Absent) }
}

impl<T: ::serde::Serialize> ::serde::Serialize for EssPresence<T> {
    fn serialize<S: ::serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::Present(value) => ::serde::Serialize::serialize(value, serializer),
            Self::Absent => Err(::serde::ser::Error::custom("absent is not a JSON value")),
        }
    }
}

impl<'de, T: ::serde::Deserialize<'de>> ::serde::Deserialize<'de> for EssPresence<T> {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        T::deserialize(deserializer).map(Self::Present)
    }
}

/// A required nullable field must still exist in its containing object.
pub fn ess_required<'de, D: ::serde::Deserializer<'de>, T: ::serde::Deserialize<'de>>(deserializer: D) -> Result<T, D::Error> {
    T::deserialize(deserializer)
}

/// The value set of JSON Schema false is empty.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssNever {}

// Source: "/$defs/mcp.http_observations.MessageLength/oneOf/1/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape06892d621a5e1e56 {
    #[serde(rename = "exact")]
    V0,
}

// Source: "/$defs/mcp.http_exchange.ExchangeResult/oneOf/2/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape0cae61a3ac6e4d23 {
    #[serde(rename = "result")]
    V0,
}

// Source: "/$defs/mcp.http_observations.PeerData/oneOf/1/properties/presence"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape1b59ccd44ecb8bce {
    #[serde(rename = "present")]
    V0,
}

// Source: "/$defs/mcp.http_exchange.RequestId/oneOf/0"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShape234fa6eff7ed7cd4 {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShape72ca42c9b2acb03d,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::serde_json::Number,
}

// Source: "/$defs/mcp.http_exchange.ExchangeResult/oneOf/0"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShape28c6237ce6c5ecea {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShape9e6725b20de0262d,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpExchangePeerErrorResult>,
}

// Source: "/$defs/mcp.http_exchange.RequestId/oneOf/1"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShape2e2034ef4e783549 {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShapeab3cfc76d3a29583,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::string::String,
}

// Source: "/$defs/mcp.http_observations.MessageLength/oneOf/0/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape36f0291c212045d7 {
    #[serde(rename = "at_least")]
    V0,
}

// Source: "/$defs/mcp.http_exchange.ExchangeResult/oneOf/1/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape406e8d5290b81cac {
    #[serde(rename = "refused")]
    V0,
}

// Source: "/$defs/mcp.http_observations.PeerData/oneOf/0/properties/presence"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape549e17263ab10eb7 {
    #[serde(rename = "absent")]
    V0,
}

// Source: "/$defs/mcp.http_observations.PeerData/oneOf/0"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShape57140dd945206401 {
    #[serde(rename = "presence")]
    #[serde(deserialize_with = "ess_required")]
    pub presence: EssShape549e17263ab10eb7,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpObservationsAbsentPeerData>,
}

// Source: "/$defs/mcp.http_exchange.ExchangeResult/oneOf/2"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShape6175a8f47058d8dd {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShape0cae61a3ac6e4d23,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpExchangeCompleteResult>,
}

// Source: "/$defs/mcp.http_exchange.RequestId/oneOf/0/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape72ca42c9b2acb03d {
    #[serde(rename = "integer")]
    V0,
}

// Source: "/$defs/mcp.http_observations.PeerData/oneOf/1"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShape89ba6ab534731e6f {
    #[serde(rename = "presence")]
    #[serde(deserialize_with = "ess_required")]
    pub presence: EssShape1b59ccd44ecb8bce,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::serde_json::Value,
}

// Source: "/$defs/mcp.http_exchange.ExchangeResult/oneOf/0/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape9e6725b20de0262d {
    #[serde(rename = "peer_error")]
    V0,
}

// Source: "/$defs/mcp.http_exchange.RequestId/oneOf/1/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShapeab3cfc76d3a29583 {
    #[serde(rename = "string")]
    V0,
}

// Source: "/$defs/mcp.http_exchange.ExchangeResult/oneOf/1"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShapeb43b8306146655d4 {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShape406e8d5290b81cac,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpExchangeRefusedExchange>,
}

// Source: "/$defs/mcp.http_observations.MessageLength/oneOf/0"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShapedf260743e534db96 {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShape36f0291c212045d7,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpObservationsOctetCount>,
}

// Source: "/$defs/mcp.http_observations.MessageLength/oneOf/1"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShapee01f56b0270720cc {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShape06892d621a5e1e56,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpObservationsOctetCount>,
}

// Source: "/$defs/mcp.http_connection.CacheHints"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpConnectionCacheHints {
    #[serde(rename = "scope")]
    #[serde(deserialize_with = "ess_required")]
    pub scope: ::std::boxed::Box<McpHttpConnectionCacheScope>,
    #[serde(rename = "ttl_ms")]
    #[serde(deserialize_with = "ess_required")]
    pub ttl_ms: ::serde_json::Number,
}

// Source: "/$defs/mcp.http_connection.CacheScope"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpConnectionCacheScope {
    #[serde(rename = "private")]
    V0,
    #[serde(rename = "public")]
    V1,
}

// Source: "/$defs/mcp.http_connection.ImplementationInfo"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpConnectionImplementationInfo {
    #[serde(rename = "name")]
    #[serde(deserialize_with = "ess_required")]
    pub name: ::std::string::String,
    #[serde(rename = "version")]
    #[serde(deserialize_with = "ess_required")]
    pub version: ::std::string::String,
}

// Source: "/$defs/mcp.http_connection.ListCapability"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpConnectionListCapability {
    #[serde(rename = "list_changed")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub list_changed: EssPresence<bool>,
}

// Source: "/$defs/mcp.http_connection.PeerDescription"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpConnectionPeerDescription {
    #[serde(rename = "cache_hints")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub cache_hints: EssPresence<::std::boxed::Box<McpHttpConnectionCacheHints>>,
    #[serde(rename = "capabilities")]
    #[serde(deserialize_with = "ess_required")]
    pub capabilities: ::std::boxed::Box<McpHttpConnectionServerCapabilities>,
    #[serde(rename = "configured_revision")]
    #[serde(deserialize_with = "ess_required")]
    pub configured_revision: ::std::boxed::Box<McpHttpObservationsProtocolRevision>,
    #[serde(rename = "exchange_observation")]
    #[serde(deserialize_with = "ess_required")]
    pub exchange_observation: ::std::boxed::Box<McpHttpExchangeExchangeObservation>,
    #[serde(rename = "instructions")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub instructions: EssPresence<::std::string::String>,
    #[serde(rename = "raw_result")]
    #[serde(deserialize_with = "ess_required")]
    pub raw_result: ::serde_json::Value,
    #[serde(rename = "reported_versions")]
    #[serde(deserialize_with = "ess_required")]
    pub reported_versions: ::std::vec::Vec<::std::string::String>,
    #[serde(rename = "server_info")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub server_info: EssPresence<::std::boxed::Box<McpHttpConnectionImplementationInfo>>,
}

// Source: "/$defs/mcp.http_connection.ResourceCapability"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpConnectionResourceCapability {
    #[serde(rename = "list_changed")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub list_changed: EssPresence<bool>,
    #[serde(rename = "subscribe")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub subscribe: EssPresence<bool>,
}

// Source: "/$defs/mcp.http_connection.ServerCapabilities"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpConnectionServerCapabilities {
    #[serde(rename = "prompts")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub prompts: EssPresence<::std::boxed::Box<McpHttpConnectionListCapability>>,
    #[serde(rename = "reported_keys")]
    #[serde(deserialize_with = "ess_required")]
    pub reported_keys: ::std::vec::Vec<::std::string::String>,
    #[serde(rename = "resources")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub resources: EssPresence<::std::boxed::Box<McpHttpConnectionResourceCapability>>,
    #[serde(rename = "tools")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub tools: EssPresence<::std::boxed::Box<McpHttpConnectionListCapability>>,
}

// Source: "/$defs/mcp.http_connection.SetupInput"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpConnectionSetupInput {
    #[serde(rename = "budget")]
    #[serde(deserialize_with = "ess_required")]
    pub budget: ::std::boxed::Box<McpHttpExchangeExchangeBudget>,
    #[serde(rename = "client_info")]
    #[serde(deserialize_with = "ess_required")]
    pub client_info: ::std::boxed::Box<McpHttpConnectionImplementationInfo>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "ess_required")]
    pub revision: ::std::boxed::Box<McpHttpObservationsProtocolRevision>,
    #[serde(rename = "session_id_octets")]
    #[serde(deserialize_with = "ess_required")]
    pub session_id_octets: ::std::boxed::Box<McpHttpObservationsOctetCount>,
}

// Source: "/$defs/mcp.http_connection.SetupRefusal"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpConnectionSetupRefusal {
    #[serde(rename = "exchange")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub exchange: EssPresence<::std::boxed::Box<McpHttpExchangeExchangeResult>>,
    #[serde(rename = "notification")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub notification: EssPresence<::std::boxed::Box<McpHttpExchangeExchangeObservation>>,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "ess_required")]
    pub reason: ::std::boxed::Box<McpHttpConnectionSetupRefusalReason>,
}

// Source: "/$defs/mcp.http_connection.SetupRefusalReason"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpConnectionSetupRefusalReason {
    #[serde(rename = "deadline_exhausted")]
    V0,
    #[serde(rename = "exchange_refused")]
    V1,
    #[serde(rename = "invalid_description")]
    V2,
    #[serde(rename = "invalid_input")]
    V3,
    #[serde(rename = "invalid_session_header")]
    V4,
    #[serde(rename = "notification_refused")]
    V5,
    #[serde(rename = "peer_error")]
    V6,
    #[serde(rename = "revision_mismatch")]
    V7,
    #[serde(rename = "session_header_bound")]
    V8,
}

// Source: "/$defs/mcp.http_exchange.CompleteResult"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpExchangeCompleteResult {
    #[serde(rename = "observation")]
    #[serde(deserialize_with = "ess_required")]
    pub observation: ::std::boxed::Box<McpHttpExchangeExchangeObservation>,
    #[serde(rename = "result")]
    #[serde(deserialize_with = "ess_required")]
    pub result: ::serde_json::Value,
}

// Source: "/$defs/mcp.http_exchange.ExchangeBudget"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpExchangeExchangeBudget {
    #[serde(rename = "connect_ms")]
    #[serde(deserialize_with = "ess_required")]
    pub connect_ms: ::std::boxed::Box<McpHttpExchangePositiveMilliseconds>,
    #[serde(rename = "provider_ms")]
    #[serde(deserialize_with = "ess_required")]
    pub provider_ms: ::std::boxed::Box<McpHttpExchangePositiveMilliseconds>,
    #[serde(rename = "remaining_execution_ms")]
    #[serde(deserialize_with = "ess_required")]
    pub remaining_execution_ms: ::std::boxed::Box<McpHttpExchangePositiveMilliseconds>,
    #[serde(rename = "request_octets")]
    #[serde(deserialize_with = "ess_required")]
    pub request_octets: ::std::boxed::Box<McpHttpObservationsOctetCount>,
    #[serde(rename = "response_octets")]
    #[serde(deserialize_with = "ess_required")]
    pub response_octets: ::std::boxed::Box<McpHttpObservationsOctetCount>,
    #[serde(rename = "sse_event_octets")]
    #[serde(deserialize_with = "ess_required")]
    pub sse_event_octets: ::std::boxed::Box<McpHttpObservationsOctetCount>,
}

// Source: "/$defs/mcp.http_exchange.ExchangeInput"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpExchangeExchangeInput {
    #[serde(rename = "budget")]
    #[serde(deserialize_with = "ess_required")]
    pub budget: ::std::boxed::Box<McpHttpExchangeExchangeBudget>,
    #[serde(rename = "encoded_request")]
    #[serde(deserialize_with = "ess_required")]
    pub encoded_request: ::std::string::String,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "ess_required")]
    pub request_id: ::std::boxed::Box<McpHttpExchangeRequestId>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "ess_required")]
    pub revision: ::std::boxed::Box<McpHttpObservationsProtocolRevision>,
}

// Source: "/$defs/mcp.http_exchange.ExchangeObservation"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpExchangeExchangeObservation {
    #[serde(rename = "http_status")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub http_status: EssPresence<::std::boxed::Box<McpHttpExchangeHttpStatus>>,
    #[serde(rename = "response")]
    #[serde(deserialize_with = "ess_required")]
    pub response: ::std::boxed::Box<McpHttpObservationsBoundedWireBytes>,
    #[serde(rename = "send")]
    #[serde(deserialize_with = "ess_required")]
    pub send: ::std::boxed::Box<McpHttpObservationsSendObservation>,
    #[serde(rename = "terminal")]
    #[serde(deserialize_with = "ess_required")]
    pub terminal: ::std::boxed::Box<McpHttpObservationsTerminalObservation>,
}

// Source: "/$defs/mcp.http_exchange.ExchangeResult"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
#[serde(untagged)]
pub enum McpHttpExchangeExchangeResult {
    V0(EssShape28c6237ce6c5ecea),
    V1(EssShapeb43b8306146655d4),
    V2(EssShape6175a8f47058d8dd),
}
impl<'de> ::serde::Deserialize<'de> for McpHttpExchangeExchangeResult {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;
        if let Ok(decoded) = ::serde_json::from_value::<EssShape28c6237ce6c5ecea>(value.clone()) {
            return Ok(Self::V0(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShapeb43b8306146655d4>(value.clone()) {
            return Ok(Self::V1(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShape6175a8f47058d8dd>(value.clone()) {
            return Ok(Self::V2(decoded));
        }
        Err(::serde::de::Error::custom("no structurally decodable union alternative"))
    }
}

// Source: "/$defs/mcp.http_exchange.HttpStatus"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(transparent)]
pub struct McpHttpExchangeHttpStatus(pub ::serde_json::Number);

// Source: "/$defs/mcp.http_exchange.PeerErrorResult"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpExchangePeerErrorResult {
    #[serde(rename = "error")]
    #[serde(deserialize_with = "ess_required")]
    pub error: ::std::boxed::Box<McpHttpObservationsPeerError>,
    #[serde(rename = "observation")]
    #[serde(deserialize_with = "ess_required")]
    pub observation: ::std::boxed::Box<McpHttpExchangeExchangeObservation>,
}

// Source: "/$defs/mcp.http_exchange.PositiveMilliseconds"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(transparent)]
pub struct McpHttpExchangePositiveMilliseconds(pub ::serde_json::Number);

// Source: "/$defs/mcp.http_exchange.RefusalReason"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpExchangeRefusalReason {
    #[serde(rename = "authorization_required")]
    V0,
    #[serde(rename = "deadline_exhausted")]
    V1,
    #[serde(rename = "http_status")]
    V2,
    #[serde(rename = "invalid_input")]
    V3,
    #[serde(rename = "invalid_response")]
    V4,
    #[serde(rename = "request_bound")]
    V5,
    #[serde(rename = "response_bound")]
    V6,
    #[serde(rename = "session_expired")]
    V7,
    #[serde(rename = "sse_event_bound")]
    V8,
    #[serde(rename = "transport_failure")]
    V9,
    #[serde(rename = "unsupported_response")]
    V10,
}

// Source: "/$defs/mcp.http_exchange.RefusedExchange"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpExchangeRefusedExchange {
    #[serde(rename = "observation")]
    #[serde(deserialize_with = "ess_required")]
    pub observation: ::std::boxed::Box<McpHttpExchangeExchangeObservation>,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "ess_required")]
    pub reason: ::std::boxed::Box<McpHttpExchangeRefusalReason>,
}

// Source: "/$defs/mcp.http_exchange.RequestId"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
#[serde(untagged)]
pub enum McpHttpExchangeRequestId {
    V0(EssShape234fa6eff7ed7cd4),
    V1(EssShape2e2034ef4e783549),
}
impl<'de> ::serde::Deserialize<'de> for McpHttpExchangeRequestId {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;
        if let Ok(decoded) = ::serde_json::from_value::<EssShape234fa6eff7ed7cd4>(value.clone()) {
            return Ok(Self::V0(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShape2e2034ef4e783549>(value.clone()) {
            return Ok(Self::V1(decoded));
        }
        Err(::serde::de::Error::custom("no structurally decodable union alternative"))
    }
}

// Source: "/$defs/mcp.http_observations.AbsentPeerData"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpObservationsAbsentPeerData {
    #[serde(rename = "absent")]
    V0,
}

// Source: "/$defs/mcp.http_observations.BoundedWireBytes"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpObservationsBoundedWireBytes {
    #[serde(rename = "bytes")]
    #[serde(deserialize_with = "ess_required")]
    pub bytes: ::std::string::String,
    #[serde(rename = "counts")]
    #[serde(deserialize_with = "ess_required")]
    pub counts: ::std::boxed::Box<McpHttpObservationsRetentionCounts>,
    #[serde(rename = "message_length")]
    #[serde(deserialize_with = "ess_required")]
    pub message_length: ::std::boxed::Box<McpHttpObservationsMessageLength>,
    #[serde(rename = "retention")]
    #[serde(deserialize_with = "ess_required")]
    pub retention: ::std::boxed::Box<McpHttpObservationsRetentionKind>,
}

// Source: "/$defs/mcp.http_observations.MessageLength"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
#[serde(untagged)]
pub enum McpHttpObservationsMessageLength {
    V0(EssShapedf260743e534db96),
    V1(EssShapee01f56b0270720cc),
}
impl<'de> ::serde::Deserialize<'de> for McpHttpObservationsMessageLength {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;
        if let Ok(decoded) = ::serde_json::from_value::<EssShapedf260743e534db96>(value.clone()) {
            return Ok(Self::V0(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShapee01f56b0270720cc>(value.clone()) {
            return Ok(Self::V1(decoded));
        }
        Err(::serde::de::Error::custom("no structurally decodable union alternative"))
    }
}

// Source: "/$defs/mcp.http_observations.OctetCount"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(transparent)]
pub struct McpHttpObservationsOctetCount(pub ::serde_json::Number);

// Source: "/$defs/mcp.http_observations.PeerData"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
#[serde(untagged)]
pub enum McpHttpObservationsPeerData {
    V0(EssShape57140dd945206401),
    V1(EssShape89ba6ab534731e6f),
}
impl<'de> ::serde::Deserialize<'de> for McpHttpObservationsPeerData {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;
        if let Ok(decoded) = ::serde_json::from_value::<EssShape57140dd945206401>(value.clone()) {
            return Ok(Self::V0(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShape89ba6ab534731e6f>(value.clone()) {
            return Ok(Self::V1(decoded));
        }
        Err(::serde::de::Error::custom("no structurally decodable union alternative"))
    }
}

// Source: "/$defs/mcp.http_observations.PeerError"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpObservationsPeerError {
    #[serde(rename = "code")]
    #[serde(deserialize_with = "ess_required")]
    pub code: ::serde_json::Number,
    #[serde(rename = "data")]
    #[serde(deserialize_with = "ess_required")]
    pub data: ::std::boxed::Box<McpHttpObservationsPeerData>,
    #[serde(rename = "message")]
    #[serde(deserialize_with = "ess_required")]
    pub message: ::std::string::String,
}

// Source: "/$defs/mcp.http_observations.ProtocolRevision"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpObservationsProtocolRevision {
    #[serde(rename = "2025-11-25")]
    V0,
    #[serde(rename = "2026-07-28")]
    V1,
}

// Source: "/$defs/mcp.http_observations.RetentionCounts"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpObservationsRetentionCounts {
    #[serde(rename = "limit_octets")]
    #[serde(deserialize_with = "ess_required")]
    pub limit_octets: ::std::boxed::Box<McpHttpObservationsOctetCount>,
    #[serde(rename = "retained_octets")]
    #[serde(deserialize_with = "ess_required")]
    pub retained_octets: ::std::boxed::Box<McpHttpObservationsOctetCount>,
}

// Source: "/$defs/mcp.http_observations.RetentionKind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpObservationsRetentionKind {
    #[serde(rename = "prefix")]
    V0,
    #[serde(rename = "whole_message")]
    V1,
}

// Source: "/$defs/mcp.http_observations.SendObservation"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpObservationsSendObservation {
    #[serde(rename = "not_sent")]
    V0,
    #[serde(rename = "send_observed")]
    V1,
    #[serde(rename = "unknown")]
    V2,
}

// Source: "/$defs/mcp.http_observations.TerminalObservation"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpObservationsTerminalObservation {
    #[serde(rename = "correlated_terminal")]
    V0,
    #[serde(rename = "incomplete")]
    V1,
}

