// @generated by ESS 0.50.0; do not edit.
// Source SHA-256: b0f12a901b7f85240923ded66ca57b5e96d17caf4f7bfb553c9ee253bcbc03e4
// Model schema projection SHA-256: 75fcea9094a9f698a690f108c70df54f268f13ffd5260d90458b54af9716e721
// Structural serialization only; see types-report.json for runtime obligations.

/// Absence is independent of the field value, including a present JSON null.
#[derive(Debug, Clone, PartialEq)]
pub enum EssPresence<T> {
    Absent,
    Present(T),
}

impl<T> Default for EssPresence<T> {
    fn default() -> Self { Self::Absent }
}

impl<T> EssPresence<T> {
    pub fn is_absent(&self) -> bool { matches!(self, Self::Absent) }
}

impl<T: ::serde::Serialize> ::serde::Serialize for EssPresence<T> {
    fn serialize<S: ::serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::Present(value) => ::serde::Serialize::serialize(value, serializer),
            Self::Absent => Err(::serde::ser::Error::custom("absent is not a JSON value")),
        }
    }
}

impl<'de, T: ::serde::Deserialize<'de>> ::serde::Deserialize<'de> for EssPresence<T> {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        T::deserialize(deserializer).map(Self::Present)
    }
}

/// A required nullable field must still exist in its containing object.
pub fn ess_required<'de, D: ::serde::Deserializer<'de>, T: ::serde::Deserialize<'de>>(deserializer: D) -> Result<T, D::Error> {
    T::deserialize(deserializer)
}

/// The value set of JSON Schema false is empty.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssNever {}

// Source: "/$defs/mcp.http_discovery.Descriptor/oneOf/1"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShape04709eb5515314ba {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShape6330cf891520d141,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpDiscoveryResource>,
}

// Source: "/$defs/mcp.http_observations.MessageLength/oneOf/1/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape06892d621a5e1e56 {
    #[serde(rename = "exact")]
    V0,
}

// Source: "/$defs/mcp.http_lifecycle.StreamMessage/oneOf/1/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape069d5fe26a415bad {
    #[serde(rename = "progress")]
    V0,
}

// Source: "/$defs/mcp.http_exchange.ExchangeResult/oneOf/2/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape0cae61a3ac6e4d23 {
    #[serde(rename = "result")]
    V0,
}

// Source: "/$defs/mcp.http_invocation.Content/oneOf/2/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape197ac92f96324cd0 {
    #[serde(rename = "resource")]
    V0,
}

// Source: "/$defs/mcp.http_observations.PeerData/oneOf/1/properties/presence"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape1b59ccd44ecb8bce {
    #[serde(rename = "present")]
    V0,
}

// Source: "/$defs/mcp.http_invocation.Content/oneOf/1"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShape1c90253db5ce2709 {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShapedc9de70e0a92bd22,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpInvocationBinaryContent>,
}

// Source: "/$defs/mcp.http_exchange.RequestId/oneOf/0"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShape234fa6eff7ed7cd4 {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShape72ca42c9b2acb03d,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::serde_json::Number,
}

// Source: "/$defs/mcp.http_invocation.Content/oneOf/0/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape25427a972bf6c971 {
    #[serde(rename = "audio")]
    V0,
}

// Source: "/$defs/mcp.http_exchange.ExchangeResult/oneOf/0"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShape28c6237ce6c5ecea {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShape9e6725b20de0262d,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpExchangePeerErrorResult>,
}

// Source: "/$defs/mcp.http_lifecycle.StreamMessage/oneOf/1"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShape2dfd854e27e8c689 {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShape069d5fe26a415bad,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpLifecycleProgressObservation>,
}

// Source: "/$defs/mcp.http_exchange.RequestId/oneOf/1"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShape2e2034ef4e783549 {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShapeab3cfc76d3a29583,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::string::String,
}

// Source: "/$defs/mcp.http_observations.MessageLength/oneOf/0/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape36f0291c212045d7 {
    #[serde(rename = "at_least")]
    V0,
}

// Source: "/$defs/mcp.http_exchange.ExchangeResult/oneOf/1/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape406e8d5290b81cac {
    #[serde(rename = "refused")]
    V0,
}

// Source: "/$defs/mcp.http_invocation.Content/oneOf/4/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape4bc042eddf498759 {
    #[serde(rename = "text")]
    V0,
}

// Source: "/$defs/mcp.http_invocation.Content/oneOf/4"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShape4d7d526db80a87d0 {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShape4bc042eddf498759,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpInvocationTextContent>,
}

// Source: "/$defs/mcp.http_observations.PeerData/oneOf/0/properties/presence"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape549e17263ab10eb7 {
    #[serde(rename = "absent")]
    V0,
}

// Source: "/$defs/mcp.http_observations.PeerData/oneOf/0"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShape57140dd945206401 {
    #[serde(rename = "presence")]
    #[serde(deserialize_with = "ess_required")]
    pub presence: EssShape549e17263ab10eb7,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpObservationsAbsentPeerData>,
}

// Source: "/$defs/mcp.http_lifecycle.ControlledSchemaResult/oneOf/0"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShape5f3251cfdb70839c {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShape73c143b2375106d7,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpInvocationSchemaReply>,
}

// Source: "/$defs/mcp.http_exchange.ExchangeResult/oneOf/2"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShape6175a8f47058d8dd {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShape0cae61a3ac6e4d23,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpExchangeCompleteResult>,
}

// Source: "/$defs/mcp.http_discovery.Descriptor/oneOf/1/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape6330cf891520d141 {
    #[serde(rename = "resource")]
    V0,
}

// Source: "/$defs/mcp.http_exchange.RequestId/oneOf/0/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape72ca42c9b2acb03d {
    #[serde(rename = "integer")]
    V0,
}

// Source: "/$defs/mcp.http_lifecycle.ControlledSchemaResult/oneOf/0/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape73c143b2375106d7 {
    #[serde(rename = "completed")]
    V0,
}

// Source: "/$defs/mcp.http_lifecycle.StreamMessage/oneOf/2/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape7d9e2bef226e658e {
    #[serde(rename = "server_request")]
    V0,
}

// Source: "/$defs/mcp.http_invocation.Content/oneOf/3"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShape8338ff3e4549abc5 {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShapebc87d8ae86a85bf7,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpInvocationResourceLink>,
}

// Source: "/$defs/mcp.http_observations.PeerData/oneOf/1"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShape89ba6ab534731e6f {
    #[serde(rename = "presence")]
    #[serde(deserialize_with = "ess_required")]
    pub presence: EssShape1b59ccd44ecb8bce,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::serde_json::Value,
}

// Source: "/$defs/mcp.http_lifecycle.ControlledExchange/oneOf/1/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape928035217e9a3240 {
    #[serde(rename = "finished")]
    V0,
}

// Source: "/$defs/mcp.http_exchange.ExchangeResult/oneOf/0/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShape9e6725b20de0262d {
    #[serde(rename = "peer_error")]
    V0,
}

// Source: "/$defs/mcp.http_invocation.Content/oneOf/0"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShapea37a8e28ca3197c2 {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShape25427a972bf6c971,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpInvocationBinaryContent>,
}

// Source: "/$defs/mcp.http_lifecycle.ControlledSchemaResult/oneOf/1/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShapea3c1608af6fe5725 {
    #[serde(rename = "interrupted")]
    V0,
}

// Source: "/$defs/mcp.http_discovery.Descriptor/oneOf/0"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShapea5ed58e66a6ac2af {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShapeb9cef17ae4ee316d,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpDiscoveryPrompt>,
}

// Source: "/$defs/mcp.http_exchange.RequestId/oneOf/1/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShapeab3cfc76d3a29583 {
    #[serde(rename = "string")]
    V0,
}

// Source: "/$defs/mcp.http_lifecycle.ControlledExchange/oneOf/0"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShapeab4932fdb11b0759 {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShapec593b133f19ee716,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpLifecycleCancellationObservation>,
}

// Source: "/$defs/mcp.http_lifecycle.ControlledExchange/oneOf/1"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShapeb303a11909beae35 {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShape928035217e9a3240,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpExchangeExchangeResult>,
}

// Source: "/$defs/mcp.http_exchange.ExchangeResult/oneOf/1"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShapeb43b8306146655d4 {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShape406e8d5290b81cac,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpExchangeRefusedExchange>,
}

// Source: "/$defs/mcp.http_lifecycle.ControlledSchemaResult/oneOf/1"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShapeb7145fb84829d1e1 {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShapea3c1608af6fe5725,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpLifecycleWorkerInterruption>,
}

// Source: "/$defs/mcp.http_discovery.Descriptor/oneOf/0/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShapeb9cef17ae4ee316d {
    #[serde(rename = "prompt")]
    V0,
}

// Source: "/$defs/mcp.http_invocation.Content/oneOf/3/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShapebc87d8ae86a85bf7 {
    #[serde(rename = "resource_link")]
    V0,
}

// Source: "/$defs/mcp.http_discovery.Descriptor/oneOf/2"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShapec108d7902c5ad32c {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShapedb6b4ad90d39349b,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpDiscoveryTool>,
}

// Source: "/$defs/mcp.http_lifecycle.ControlledExchange/oneOf/0/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShapec593b133f19ee716 {
    #[serde(rename = "cancelled")]
    V0,
}

// Source: "/$defs/mcp.http_lifecycle.ControlledSchemaResult/oneOf/2"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShapec8aea68a93236568 {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShapee11099b58b5c7165,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpLifecycleWorkerRefusal>,
}

// Source: "/$defs/mcp.http_lifecycle.StreamMessage/oneOf/2"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShapeca3b047f4e2a5937 {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShape7d9e2bef226e658e,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpLifecycleServerRequestObservation>,
}

// Source: "/$defs/mcp.http_lifecycle.StreamMessage/oneOf/0"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShapecea226422afd802f {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShaped188c86fdc49cb63,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpExchangeWireObservation>,
}

// Source: "/$defs/mcp.http_lifecycle.StreamMessage/oneOf/0/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShaped188c86fdc49cb63 {
    #[serde(rename = "notification")]
    V0,
}

// Source: "/$defs/mcp.http_discovery.Descriptor/oneOf/2/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShapedb6b4ad90d39349b {
    #[serde(rename = "tool")]
    V0,
}

// Source: "/$defs/mcp.http_invocation.Content/oneOf/1/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShapedc9de70e0a92bd22 {
    #[serde(rename = "image")]
    V0,
}

// Source: "/$defs/mcp.http_observations.MessageLength/oneOf/0"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShapedf260743e534db96 {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShape36f0291c212045d7,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpObservationsOctetCount>,
}

// Source: "/$defs/mcp.http_observations.MessageLength/oneOf/1"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShapee01f56b0270720cc {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShape06892d621a5e1e56,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpObservationsOctetCount>,
}

// Source: "/$defs/mcp.http_lifecycle.ControlledSchemaResult/oneOf/2/properties/kind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EssShapee11099b58b5c7165 {
    #[serde(rename = "refused")]
    V0,
}

// Source: "/$defs/mcp.http_invocation.Content/oneOf/2"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EssShapefb41dfd81bd200ee {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "ess_required")]
    pub kind: EssShape197ac92f96324cd0,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "ess_required")]
    pub value: ::std::boxed::Box<McpHttpInvocationEmbeddedResource>,
}

// Source: "/$defs/mcp.http_connection.CacheHints"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpConnectionCacheHints {
    #[serde(rename = "scope")]
    #[serde(deserialize_with = "ess_required")]
    pub scope: ::std::boxed::Box<McpHttpConnectionCacheScope>,
    #[serde(rename = "ttl_ms")]
    #[serde(deserialize_with = "ess_required")]
    pub ttl_ms: ::serde_json::Number,
}

// Source: "/$defs/mcp.http_connection.CacheScope"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpConnectionCacheScope {
    #[serde(rename = "private")]
    V0,
    #[serde(rename = "public")]
    V1,
}

// Source: "/$defs/mcp.http_connection.ImplementationInfo"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpConnectionImplementationInfo {
    #[serde(rename = "name")]
    #[serde(deserialize_with = "ess_required")]
    pub name: ::std::string::String,
    #[serde(rename = "version")]
    #[serde(deserialize_with = "ess_required")]
    pub version: ::std::string::String,
}

// Source: "/$defs/mcp.http_connection.ListCapability"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpConnectionListCapability {
    #[serde(rename = "list_changed")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub list_changed: EssPresence<bool>,
}

// Source: "/$defs/mcp.http_connection.PeerDescription"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpConnectionPeerDescription {
    #[serde(rename = "cache_hints")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub cache_hints: EssPresence<::std::boxed::Box<McpHttpConnectionCacheHints>>,
    #[serde(rename = "capabilities")]
    #[serde(deserialize_with = "ess_required")]
    pub capabilities: ::std::boxed::Box<McpHttpConnectionServerCapabilities>,
    #[serde(rename = "configured_revision")]
    #[serde(deserialize_with = "ess_required")]
    pub configured_revision: ::std::boxed::Box<McpHttpObservationsProtocolRevision>,
    #[serde(rename = "exchange_observation")]
    #[serde(deserialize_with = "ess_required")]
    pub exchange_observation: ::std::boxed::Box<McpHttpExchangeExchangeObservation>,
    #[serde(rename = "instructions")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub instructions: EssPresence<::std::string::String>,
    #[serde(rename = "raw_result")]
    #[serde(deserialize_with = "ess_required")]
    pub raw_result: ::serde_json::Value,
    #[serde(rename = "reported_versions")]
    #[serde(deserialize_with = "ess_required")]
    pub reported_versions: ::std::vec::Vec<::std::string::String>,
    #[serde(rename = "server_info")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub server_info: EssPresence<::std::boxed::Box<McpHttpConnectionImplementationInfo>>,
}

// Source: "/$defs/mcp.http_connection.ResourceCapability"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpConnectionResourceCapability {
    #[serde(rename = "list_changed")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub list_changed: EssPresence<bool>,
    #[serde(rename = "subscribe")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub subscribe: EssPresence<bool>,
}

// Source: "/$defs/mcp.http_connection.ServerCapabilities"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpConnectionServerCapabilities {
    #[serde(rename = "prompts")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub prompts: EssPresence<::std::boxed::Box<McpHttpConnectionListCapability>>,
    #[serde(rename = "reported_keys")]
    #[serde(deserialize_with = "ess_required")]
    pub reported_keys: ::std::vec::Vec<::std::string::String>,
    #[serde(rename = "resources")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub resources: EssPresence<::std::boxed::Box<McpHttpConnectionResourceCapability>>,
    #[serde(rename = "tools")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub tools: EssPresence<::std::boxed::Box<McpHttpConnectionListCapability>>,
}

// Source: "/$defs/mcp.http_connection.SetupInput"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpConnectionSetupInput {
    #[serde(rename = "budget")]
    #[serde(deserialize_with = "ess_required")]
    pub budget: ::std::boxed::Box<McpHttpExchangeExchangeBudget>,
    #[serde(rename = "client_info")]
    #[serde(deserialize_with = "ess_required")]
    pub client_info: ::std::boxed::Box<McpHttpConnectionImplementationInfo>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "ess_required")]
    pub revision: ::std::boxed::Box<McpHttpObservationsProtocolRevision>,
    #[serde(rename = "session_id_octets")]
    #[serde(deserialize_with = "ess_required")]
    pub session_id_octets: ::std::boxed::Box<McpHttpObservationsOctetCount>,
}

// Source: "/$defs/mcp.http_connection.SetupRefusal"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpConnectionSetupRefusal {
    #[serde(rename = "exchange")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub exchange: EssPresence<::std::boxed::Box<McpHttpExchangeExchangeResult>>,
    #[serde(rename = "notification")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub notification: EssPresence<::std::boxed::Box<McpHttpExchangeExchangeObservation>>,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "ess_required")]
    pub reason: ::std::boxed::Box<McpHttpConnectionSetupRefusalReason>,
}

// Source: "/$defs/mcp.http_connection.SetupRefusalReason"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpConnectionSetupRefusalReason {
    #[serde(rename = "deadline_exhausted")]
    V0,
    #[serde(rename = "exchange_refused")]
    V1,
    #[serde(rename = "invalid_description")]
    V2,
    #[serde(rename = "invalid_input")]
    V3,
    #[serde(rename = "invalid_session_header")]
    V4,
    #[serde(rename = "notification_refused")]
    V5,
    #[serde(rename = "peer_error")]
    V6,
    #[serde(rename = "revision_mismatch")]
    V7,
    #[serde(rename = "session_header_bound")]
    V8,
}

// Source: "/$defs/mcp.http_discovery.Catalog"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpDiscoveryCatalog {
    #[serde(rename = "descriptors")]
    #[serde(deserialize_with = "ess_required")]
    pub descriptors: ::std::vec::Vec<::std::boxed::Box<McpHttpDiscoveryDescriptor>>,
    #[serde(rename = "family")]
    #[serde(deserialize_with = "ess_required")]
    pub family: ::std::boxed::Box<McpHttpDiscoveryFamily>,
    #[serde(rename = "pages")]
    #[serde(deserialize_with = "ess_required")]
    pub pages: ::std::vec::Vec<::std::boxed::Box<McpHttpDiscoveryPage>>,
}

// Source: "/$defs/mcp.http_discovery.Descriptor"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
#[serde(untagged)]
pub enum McpHttpDiscoveryDescriptor {
    V0(EssShapea5ed58e66a6ac2af),
    V1(EssShape04709eb5515314ba),
    V2(EssShapec108d7902c5ad32c),
}
impl<'de> ::serde::Deserialize<'de> for McpHttpDiscoveryDescriptor {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;
        if let Ok(decoded) = ::serde_json::from_value::<EssShapea5ed58e66a6ac2af>(value.clone()) {
            return Ok(Self::V0(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShape04709eb5515314ba>(value.clone()) {
            return Ok(Self::V1(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShapec108d7902c5ad32c>(value.clone()) {
            return Ok(Self::V2(decoded));
        }
        Err(::serde::de::Error::custom("no structurally decodable union alternative"))
    }
}

// Source: "/$defs/mcp.http_discovery.Family"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpDiscoveryFamily {
    #[serde(rename = "prompts")]
    V0,
    #[serde(rename = "resources")]
    V1,
    #[serde(rename = "tools")]
    V2,
}

// Source: "/$defs/mcp.http_discovery.ListLimits"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpDiscoveryListLimits {
    #[serde(rename = "descriptor_octets")]
    #[serde(deserialize_with = "ess_required")]
    pub descriptor_octets: ::std::boxed::Box<McpHttpObservationsOctetCount>,
    #[serde(rename = "max_items")]
    #[serde(deserialize_with = "ess_required")]
    pub max_items: ::serde_json::Number,
    #[serde(rename = "max_pages")]
    #[serde(deserialize_with = "ess_required")]
    pub max_pages: ::serde_json::Number,
}

// Source: "/$defs/mcp.http_discovery.Page"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpDiscoveryPage {
    #[serde(rename = "cache_hints")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub cache_hints: EssPresence<::std::boxed::Box<McpHttpConnectionCacheHints>>,
    #[serde(rename = "exchange")]
    #[serde(deserialize_with = "ess_required")]
    pub exchange: ::std::boxed::Box<McpHttpExchangeCompleteResult>,
    #[serde(rename = "next_cursor")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub next_cursor: EssPresence<::std::string::String>,
}

// Source: "/$defs/mcp.http_discovery.Prompt"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpDiscoveryPrompt {
    #[serde(rename = "arguments")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub arguments: EssPresence<::std::vec::Vec<::std::boxed::Box<McpHttpDiscoveryPromptArgument>>>,
    #[serde(rename = "description")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub description: EssPresence<::std::string::String>,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "ess_required")]
    pub name: ::std::string::String,
    #[serde(rename = "raw")]
    #[serde(deserialize_with = "ess_required")]
    pub raw: ::serde_json::Value,
    #[serde(rename = "title")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub title: EssPresence<::std::string::String>,
}

// Source: "/$defs/mcp.http_discovery.PromptArgument"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpDiscoveryPromptArgument {
    #[serde(rename = "description")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub description: EssPresence<::std::string::String>,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "ess_required")]
    pub name: ::std::string::String,
    #[serde(rename = "raw")]
    #[serde(deserialize_with = "ess_required")]
    pub raw: ::serde_json::Value,
    #[serde(rename = "required")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub required: EssPresence<bool>,
    #[serde(rename = "title")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub title: EssPresence<::std::string::String>,
}

// Source: "/$defs/mcp.http_discovery.Refusal"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpDiscoveryRefusal {
    #[serde(rename = "actual")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub actual: EssPresence<::serde_json::Number>,
    #[serde(rename = "exchanges")]
    #[serde(deserialize_with = "ess_required")]
    pub exchanges: ::std::vec::Vec<::std::boxed::Box<McpHttpExchangeExchangeResult>>,
    #[serde(rename = "limit")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub limit: EssPresence<::serde_json::Number>,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "ess_required")]
    pub reason: ::std::boxed::Box<McpHttpDiscoveryRefusalReason>,
}

// Source: "/$defs/mcp.http_discovery.RefusalReason"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpDiscoveryRefusalReason {
    #[serde(rename = "deadline_exhausted")]
    V0,
    #[serde(rename = "descriptor_limit")]
    V1,
    #[serde(rename = "duplicate_identity")]
    V2,
    #[serde(rename = "exchange_refused")]
    V3,
    #[serde(rename = "invalid_descriptor")]
    V4,
    #[serde(rename = "invalid_limits")]
    V5,
    #[serde(rename = "invalid_page")]
    V6,
    #[serde(rename = "item_limit")]
    V7,
    #[serde(rename = "page_limit")]
    V8,
    #[serde(rename = "unsupported_family")]
    V9,
    #[serde(rename = "unsupported_result")]
    V10,
}

// Source: "/$defs/mcp.http_discovery.Resource"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpDiscoveryResource {
    #[serde(rename = "description")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub description: EssPresence<::std::string::String>,
    #[serde(rename = "mime_type")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub mime_type: EssPresence<::std::string::String>,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "ess_required")]
    pub name: ::std::string::String,
    #[serde(rename = "raw")]
    #[serde(deserialize_with = "ess_required")]
    pub raw: ::serde_json::Value,
    #[serde(rename = "size")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub size: EssPresence<::serde_json::Value>,
    #[serde(rename = "title")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub title: EssPresence<::std::string::String>,
    #[serde(rename = "uri")]
    #[serde(deserialize_with = "ess_required")]
    pub uri: ::std::string::String,
}

// Source: "/$defs/mcp.http_discovery.Tool"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpDiscoveryTool {
    #[serde(rename = "description")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub description: EssPresence<::std::string::String>,
    #[serde(rename = "input_schema")]
    #[serde(deserialize_with = "ess_required")]
    pub input_schema: ::serde_json::Value,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "ess_required")]
    pub name: ::std::string::String,
    #[serde(rename = "output_schema")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub output_schema: EssPresence<::serde_json::Value>,
    #[serde(rename = "raw")]
    #[serde(deserialize_with = "ess_required")]
    pub raw: ::serde_json::Value,
    #[serde(rename = "title")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub title: EssPresence<::std::string::String>,
}

// Source: "/$defs/mcp.http_exchange.CompleteResult"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpExchangeCompleteResult {
    #[serde(rename = "observation")]
    #[serde(deserialize_with = "ess_required")]
    pub observation: ::std::boxed::Box<McpHttpExchangeExchangeObservation>,
    #[serde(rename = "result")]
    #[serde(deserialize_with = "ess_required")]
    pub result: ::serde_json::Value,
}

// Source: "/$defs/mcp.http_exchange.ExchangeBudget"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpExchangeExchangeBudget {
    #[serde(rename = "connect_ms")]
    #[serde(deserialize_with = "ess_required")]
    pub connect_ms: ::std::boxed::Box<McpHttpExchangePositiveMilliseconds>,
    #[serde(rename = "provider_ms")]
    #[serde(deserialize_with = "ess_required")]
    pub provider_ms: ::std::boxed::Box<McpHttpExchangePositiveMilliseconds>,
    #[serde(rename = "remaining_execution_ms")]
    #[serde(deserialize_with = "ess_required")]
    pub remaining_execution_ms: ::std::boxed::Box<McpHttpExchangePositiveMilliseconds>,
    #[serde(rename = "request_octets")]
    #[serde(deserialize_with = "ess_required")]
    pub request_octets: ::std::boxed::Box<McpHttpObservationsOctetCount>,
    #[serde(rename = "response_octets")]
    #[serde(deserialize_with = "ess_required")]
    pub response_octets: ::std::boxed::Box<McpHttpObservationsOctetCount>,
    #[serde(rename = "sse_event_octets")]
    #[serde(deserialize_with = "ess_required")]
    pub sse_event_octets: ::std::boxed::Box<McpHttpObservationsOctetCount>,
}

// Source: "/$defs/mcp.http_exchange.ExchangeInput"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpExchangeExchangeInput {
    #[serde(rename = "budget")]
    #[serde(deserialize_with = "ess_required")]
    pub budget: ::std::boxed::Box<McpHttpExchangeExchangeBudget>,
    #[serde(rename = "encoded_request")]
    #[serde(deserialize_with = "ess_required")]
    pub encoded_request: ::std::string::String,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "ess_required")]
    pub request_id: ::std::boxed::Box<McpHttpExchangeRequestId>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "ess_required")]
    pub revision: ::std::boxed::Box<McpHttpObservationsProtocolRevision>,
}

// Source: "/$defs/mcp.http_exchange.ExchangeObservation"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpExchangeExchangeObservation {
    #[serde(rename = "http_status")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub http_status: EssPresence<::std::boxed::Box<McpHttpExchangeHttpStatus>>,
    #[serde(rename = "response")]
    #[serde(deserialize_with = "ess_required")]
    pub response: ::std::boxed::Box<McpHttpObservationsBoundedWireBytes>,
    #[serde(rename = "send")]
    #[serde(deserialize_with = "ess_required")]
    pub send: ::std::boxed::Box<McpHttpObservationsSendObservation>,
    #[serde(rename = "stream")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub stream: EssPresence<::std::boxed::Box<McpHttpLifecycleStreamObservation>>,
    #[serde(rename = "terminal")]
    #[serde(deserialize_with = "ess_required")]
    pub terminal: ::std::boxed::Box<McpHttpObservationsTerminalObservation>,
}

// Source: "/$defs/mcp.http_exchange.ExchangeResult"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
#[serde(untagged)]
pub enum McpHttpExchangeExchangeResult {
    V0(EssShape28c6237ce6c5ecea),
    V1(EssShapeb43b8306146655d4),
    V2(EssShape6175a8f47058d8dd),
}
impl<'de> ::serde::Deserialize<'de> for McpHttpExchangeExchangeResult {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;
        if let Ok(decoded) = ::serde_json::from_value::<EssShape28c6237ce6c5ecea>(value.clone()) {
            return Ok(Self::V0(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShapeb43b8306146655d4>(value.clone()) {
            return Ok(Self::V1(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShape6175a8f47058d8dd>(value.clone()) {
            return Ok(Self::V2(decoded));
        }
        Err(::serde::de::Error::custom("no structurally decodable union alternative"))
    }
}

// Source: "/$defs/mcp.http_exchange.HttpStatus"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(transparent)]
pub struct McpHttpExchangeHttpStatus(pub ::serde_json::Number);

// Source: "/$defs/mcp.http_exchange.PeerErrorResult"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpExchangePeerErrorResult {
    #[serde(rename = "error")]
    #[serde(deserialize_with = "ess_required")]
    pub error: ::std::boxed::Box<McpHttpObservationsPeerError>,
    #[serde(rename = "observation")]
    #[serde(deserialize_with = "ess_required")]
    pub observation: ::std::boxed::Box<McpHttpExchangeExchangeObservation>,
}

// Source: "/$defs/mcp.http_exchange.PositiveMilliseconds"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(transparent)]
pub struct McpHttpExchangePositiveMilliseconds(pub ::serde_json::Number);

// Source: "/$defs/mcp.http_exchange.RefusalReason"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpExchangeRefusalReason {
    #[serde(rename = "authorization_required")]
    V0,
    #[serde(rename = "caller_cancelled")]
    V1,
    #[serde(rename = "deadline_exhausted")]
    V2,
    #[serde(rename = "http_status")]
    V3,
    #[serde(rename = "invalid_input")]
    V4,
    #[serde(rename = "invalid_response")]
    V5,
    #[serde(rename = "request_bound")]
    V6,
    #[serde(rename = "response_bound")]
    V7,
    #[serde(rename = "session_expired")]
    V8,
    #[serde(rename = "sse_event_bound")]
    V9,
    #[serde(rename = "transport_failure")]
    V10,
    #[serde(rename = "unsupported_response")]
    V11,
}

// Source: "/$defs/mcp.http_exchange.RefusedExchange"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpExchangeRefusedExchange {
    #[serde(rename = "observation")]
    #[serde(deserialize_with = "ess_required")]
    pub observation: ::std::boxed::Box<McpHttpExchangeExchangeObservation>,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "ess_required")]
    pub reason: ::std::boxed::Box<McpHttpExchangeRefusalReason>,
}

// Source: "/$defs/mcp.http_exchange.RequestId"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
#[serde(untagged)]
pub enum McpHttpExchangeRequestId {
    V0(EssShape234fa6eff7ed7cd4),
    V1(EssShape2e2034ef4e783549),
}
impl<'de> ::serde::Deserialize<'de> for McpHttpExchangeRequestId {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;
        if let Ok(decoded) = ::serde_json::from_value::<EssShape234fa6eff7ed7cd4>(value.clone()) {
            return Ok(Self::V0(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShape2e2034ef4e783549>(value.clone()) {
            return Ok(Self::V1(decoded));
        }
        Err(::serde::de::Error::custom("no structurally decodable union alternative"))
    }
}

// Source: "/$defs/mcp.http_exchange.WireObservation"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpExchangeWireObservation {
    #[serde(rename = "http_status")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub http_status: EssPresence<::std::boxed::Box<McpHttpExchangeHttpStatus>>,
    #[serde(rename = "response")]
    #[serde(deserialize_with = "ess_required")]
    pub response: ::std::boxed::Box<McpHttpObservationsBoundedWireBytes>,
    #[serde(rename = "send")]
    #[serde(deserialize_with = "ess_required")]
    pub send: ::std::boxed::Box<McpHttpObservationsSendObservation>,
    #[serde(rename = "terminal")]
    #[serde(deserialize_with = "ess_required")]
    pub terminal: ::std::boxed::Box<McpHttpObservationsTerminalObservation>,
}

// Source: "/$defs/mcp.http_invocation.BinaryContent"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpInvocationBinaryContent {
    #[serde(rename = "data")]
    #[serde(deserialize_with = "ess_required")]
    pub data: ::std::string::String,
    #[serde(rename = "mime_type")]
    #[serde(deserialize_with = "ess_required")]
    pub mime_type: ::std::string::String,
    #[serde(rename = "raw")]
    #[serde(deserialize_with = "ess_required")]
    pub raw: ::serde_json::Value,
}

// Source: "/$defs/mcp.http_invocation.Content"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
#[serde(untagged)]
pub enum McpHttpInvocationContent {
    V0(EssShapea37a8e28ca3197c2),
    V1(EssShape1c90253db5ce2709),
    V2(EssShapefb41dfd81bd200ee),
    V3(EssShape8338ff3e4549abc5),
    V4(EssShape4d7d526db80a87d0),
}
impl<'de> ::serde::Deserialize<'de> for McpHttpInvocationContent {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;
        if let Ok(decoded) = ::serde_json::from_value::<EssShapea37a8e28ca3197c2>(value.clone()) {
            return Ok(Self::V0(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShape1c90253db5ce2709>(value.clone()) {
            return Ok(Self::V1(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShapefb41dfd81bd200ee>(value.clone()) {
            return Ok(Self::V2(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShape8338ff3e4549abc5>(value.clone()) {
            return Ok(Self::V3(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShape4d7d526db80a87d0>(value.clone()) {
            return Ok(Self::V4(decoded));
        }
        Err(::serde::de::Error::custom("no structurally decodable union alternative"))
    }
}

// Source: "/$defs/mcp.http_invocation.EmbeddedResource"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpInvocationEmbeddedResource {
    #[serde(rename = "raw")]
    #[serde(deserialize_with = "ess_required")]
    pub raw: ::serde_json::Value,
    #[serde(rename = "resource")]
    #[serde(deserialize_with = "ess_required")]
    pub resource: ::std::boxed::Box<McpHttpInvocationResourceContent>,
}

// Source: "/$defs/mcp.http_invocation.HeaderPrimitive"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpInvocationHeaderPrimitive {
    #[serde(rename = "boolean")]
    V0,
    #[serde(rename = "integer")]
    V1,
    #[serde(rename = "string")]
    V2,
}

// Source: "/$defs/mcp.http_invocation.HeaderRefusalReason"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpInvocationHeaderRefusalReason {
    #[serde(rename = "duplicate_name")]
    V0,
    #[serde(rename = "invalid_location")]
    V1,
    #[serde(rename = "invalid_name")]
    V2,
    #[serde(rename = "invalid_type")]
    V3,
}

// Source: "/$defs/mcp.http_invocation.ParameterHeader"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpInvocationParameterHeader {
    #[serde(rename = "parameter_path")]
    #[serde(deserialize_with = "ess_required")]
    pub parameter_path: ::std::vec::Vec<::std::string::String>,
    #[serde(rename = "primitive")]
    #[serde(deserialize_with = "ess_required")]
    pub primitive: ::std::boxed::Box<McpHttpInvocationHeaderPrimitive>,
    #[serde(rename = "suffix")]
    #[serde(deserialize_with = "ess_required")]
    pub suffix: ::std::string::String,
}

// Source: "/$defs/mcp.http_invocation.PromptMessage"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpInvocationPromptMessage {
    #[serde(rename = "content")]
    #[serde(deserialize_with = "ess_required")]
    pub content: ::std::boxed::Box<McpHttpInvocationContent>,
    #[serde(rename = "raw")]
    #[serde(deserialize_with = "ess_required")]
    pub raw: ::serde_json::Value,
    #[serde(rename = "role")]
    #[serde(deserialize_with = "ess_required")]
    pub role: ::std::boxed::Box<McpHttpInvocationRole>,
}

// Source: "/$defs/mcp.http_invocation.PromptResult"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpInvocationPromptResult {
    #[serde(rename = "description")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub description: EssPresence<::std::string::String>,
    #[serde(rename = "exchange")]
    #[serde(deserialize_with = "ess_required")]
    pub exchange: ::std::boxed::Box<McpHttpExchangeCompleteResult>,
    #[serde(rename = "messages")]
    #[serde(deserialize_with = "ess_required")]
    pub messages: ::std::vec::Vec<::std::boxed::Box<McpHttpInvocationPromptMessage>>,
}

// Source: "/$defs/mcp.http_invocation.Refusal"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpInvocationRefusal {
    #[serde(rename = "exchange")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub exchange: EssPresence<::std::boxed::Box<McpHttpExchangeExchangeResult>>,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "ess_required")]
    pub reason: ::std::boxed::Box<McpHttpInvocationRefusalReason>,
}

// Source: "/$defs/mcp.http_invocation.RefusalReason"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpInvocationRefusalReason {
    #[serde(rename = "deadline_exhausted")]
    V0,
    #[serde(rename = "exchange_refused")]
    V1,
    #[serde(rename = "invalid_input")]
    V2,
    #[serde(rename = "invalid_result")]
    V3,
    #[serde(rename = "output_schema_mismatch")]
    V4,
    #[serde(rename = "schema_unavailable")]
    V5,
    #[serde(rename = "unknown_item")]
    V6,
    #[serde(rename = "unsupported_content")]
    V7,
    #[serde(rename = "unsupported_family")]
    V8,
    #[serde(rename = "unsupported_result")]
    V9,
    #[serde(rename = "unsupported_schema")]
    V10,
}

// Source: "/$defs/mcp.http_invocation.RejectedTool"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpInvocationRejectedTool {
    #[serde(rename = "name")]
    #[serde(deserialize_with = "ess_required")]
    pub name: ::std::string::String,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "ess_required")]
    pub reason: ::std::boxed::Box<McpHttpInvocationHeaderRefusalReason>,
}

// Source: "/$defs/mcp.http_invocation.ResourceContent"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpInvocationResourceContent {
    #[serde(rename = "blob")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub blob: EssPresence<::std::string::String>,
    #[serde(rename = "mime_type")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub mime_type: EssPresence<::std::string::String>,
    #[serde(rename = "raw")]
    #[serde(deserialize_with = "ess_required")]
    pub raw: ::serde_json::Value,
    #[serde(rename = "text")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub text: EssPresence<::std::string::String>,
    #[serde(rename = "uri")]
    #[serde(deserialize_with = "ess_required")]
    pub uri: ::std::string::String,
}

// Source: "/$defs/mcp.http_invocation.ResourceLink"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpInvocationResourceLink {
    #[serde(rename = "raw")]
    #[serde(deserialize_with = "ess_required")]
    pub raw: ::serde_json::Value,
    #[serde(rename = "resource")]
    #[serde(deserialize_with = "ess_required")]
    pub resource: ::std::boxed::Box<McpHttpDiscoveryResource>,
}

// Source: "/$defs/mcp.http_invocation.ResourceResult"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpInvocationResourceResult {
    #[serde(rename = "cache_hints")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub cache_hints: EssPresence<::std::boxed::Box<McpHttpConnectionCacheHints>>,
    #[serde(rename = "contents")]
    #[serde(deserialize_with = "ess_required")]
    pub contents: ::std::vec::Vec<::std::boxed::Box<McpHttpInvocationResourceContent>>,
    #[serde(rename = "exchange")]
    #[serde(deserialize_with = "ess_required")]
    pub exchange: ::std::boxed::Box<McpHttpExchangeCompleteResult>,
}

// Source: "/$defs/mcp.http_invocation.Role"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpInvocationRole {
    #[serde(rename = "assistant")]
    V0,
    #[serde(rename = "user")]
    V1,
}

// Source: "/$defs/mcp.http_invocation.SchemaAction"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpInvocationSchemaAction {
    #[serde(rename = "compile")]
    V0,
    #[serde(rename = "validate")]
    V1,
}

// Source: "/$defs/mcp.http_invocation.SchemaReply"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpInvocationSchemaReply {
    #[serde(rename = "status")]
    #[serde(deserialize_with = "ess_required")]
    pub status: ::std::boxed::Box<McpHttpInvocationSchemaStatus>,
}

// Source: "/$defs/mcp.http_invocation.SchemaRequest"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpInvocationSchemaRequest {
    #[serde(rename = "action")]
    #[serde(deserialize_with = "ess_required")]
    pub action: ::std::boxed::Box<McpHttpInvocationSchemaAction>,
    #[serde(rename = "instance")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub instance: EssPresence<::serde_json::Value>,
    #[serde(rename = "schema")]
    #[serde(deserialize_with = "ess_required")]
    pub schema: ::serde_json::Value,
}

// Source: "/$defs/mcp.http_invocation.SchemaStatus"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpInvocationSchemaStatus {
    #[serde(rename = "invalid_instance")]
    V0,
    #[serde(rename = "invalid_request")]
    V1,
    #[serde(rename = "invalid_schema")]
    V2,
    #[serde(rename = "unsupported_schema")]
    V3,
    #[serde(rename = "valid")]
    V4,
    #[serde(rename = "validation_unavailable")]
    V5,
}

// Source: "/$defs/mcp.http_invocation.TextContent"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpInvocationTextContent {
    #[serde(rename = "raw")]
    #[serde(deserialize_with = "ess_required")]
    pub raw: ::serde_json::Value,
    #[serde(rename = "text")]
    #[serde(deserialize_with = "ess_required")]
    pub text: ::std::string::String,
}

// Source: "/$defs/mcp.http_invocation.ToolResult"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpInvocationToolResult {
    #[serde(rename = "content")]
    #[serde(deserialize_with = "ess_required")]
    pub content: ::std::vec::Vec<::std::boxed::Box<McpHttpInvocationContent>>,
    #[serde(rename = "exchange")]
    #[serde(deserialize_with = "ess_required")]
    pub exchange: ::std::boxed::Box<McpHttpExchangeCompleteResult>,
    #[serde(rename = "is_error")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub is_error: EssPresence<bool>,
    #[serde(rename = "structured_content")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub structured_content: EssPresence<::serde_json::Value>,
}

// Source: "/$defs/mcp.http_lifecycle.CancellationObservation"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpLifecycleCancellationObservation {
    #[serde(rename = "interrupted")]
    #[serde(deserialize_with = "ess_required")]
    pub interrupted: ::std::boxed::Box<McpHttpLifecycleInterruptedRequest>,
    #[serde(rename = "late_response")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub late_response: EssPresence<::std::boxed::Box<McpHttpExchangeExchangeObservation>>,
    #[serde(rename = "notification")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub notification: EssPresence<::std::boxed::Box<McpHttpLifecycleControlObservation>>,
}

// Source: "/$defs/mcp.http_lifecycle.ControlDisposition"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpLifecycleControlDisposition {
    #[serde(rename = "accepted")]
    V0,
    #[serde(rename = "delete_not_allowed")]
    V1,
    #[serde(rename = "refused")]
    V2,
}

// Source: "/$defs/mcp.http_lifecycle.ControlKind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpLifecycleControlKind {
    #[serde(rename = "cancellation_notification")]
    V0,
    #[serde(rename = "ping_reply")]
    V1,
    #[serde(rename = "session_delete")]
    V2,
    #[serde(rename = "unsupported_request_reply")]
    V3,
}

// Source: "/$defs/mcp.http_lifecycle.ControlObservation"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpLifecycleControlObservation {
    #[serde(rename = "control")]
    #[serde(deserialize_with = "ess_required")]
    pub control: ::std::boxed::Box<McpHttpLifecycleControlKind>,
    #[serde(rename = "disposition")]
    #[serde(deserialize_with = "ess_required")]
    pub disposition: ::std::boxed::Box<McpHttpLifecycleControlDisposition>,
    #[serde(rename = "exchange")]
    #[serde(deserialize_with = "ess_required")]
    pub exchange: ::std::boxed::Box<McpHttpExchangeWireObservation>,
    #[serde(rename = "refusal")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub refusal: EssPresence<::std::boxed::Box<McpHttpExchangeRefusalReason>>,
}

// Source: "/$defs/mcp.http_lifecycle.ControlledExchange"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
#[serde(untagged)]
pub enum McpHttpLifecycleControlledExchange {
    V0(EssShapeab4932fdb11b0759),
    V1(EssShapeb303a11909beae35),
}
impl<'de> ::serde::Deserialize<'de> for McpHttpLifecycleControlledExchange {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;
        if let Ok(decoded) = ::serde_json::from_value::<EssShapeab4932fdb11b0759>(value.clone()) {
            return Ok(Self::V0(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShapeb303a11909beae35>(value.clone()) {
            return Ok(Self::V1(decoded));
        }
        Err(::serde::de::Error::custom("no structurally decodable union alternative"))
    }
}

// Source: "/$defs/mcp.http_lifecycle.ControlledSchemaResult"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
#[serde(untagged)]
pub enum McpHttpLifecycleControlledSchemaResult {
    V0(EssShape5f3251cfdb70839c),
    V1(EssShapeb7145fb84829d1e1),
    V2(EssShapec8aea68a93236568),
}
impl<'de> ::serde::Deserialize<'de> for McpHttpLifecycleControlledSchemaResult {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;
        if let Ok(decoded) = ::serde_json::from_value::<EssShape5f3251cfdb70839c>(value.clone()) {
            return Ok(Self::V0(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShapeb7145fb84829d1e1>(value.clone()) {
            return Ok(Self::V1(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShapec8aea68a93236568>(value.clone()) {
            return Ok(Self::V2(decoded));
        }
        Err(::serde::de::Error::custom("no structurally decodable union alternative"))
    }
}

// Source: "/$defs/mcp.http_lifecycle.InterruptedRequest"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpLifecycleInterruptedRequest {
    #[serde(rename = "cause")]
    #[serde(deserialize_with = "ess_required")]
    pub cause: ::std::boxed::Box<McpHttpLifecycleStopCause>,
    #[serde(rename = "exchange")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub exchange: EssPresence<::std::boxed::Box<McpHttpExchangeExchangeObservation>>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "ess_required")]
    pub request_id: ::std::boxed::Box<McpHttpExchangeRequestId>,
}

// Source: "/$defs/mcp.http_lifecycle.ProgressDisposition"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpLifecycleProgressDisposition {
    #[serde(rename = "accepted")]
    V0,
    #[serde(rename = "non_increasing")]
    V1,
    #[serde(rename = "unmatched_token")]
    V2,
}

// Source: "/$defs/mcp.http_lifecycle.ProgressObservation"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpLifecycleProgressObservation {
    #[serde(rename = "disposition")]
    #[serde(deserialize_with = "ess_required")]
    pub disposition: ::std::boxed::Box<McpHttpLifecycleProgressDisposition>,
    #[serde(rename = "exchange")]
    #[serde(deserialize_with = "ess_required")]
    pub exchange: ::std::boxed::Box<McpHttpExchangeWireObservation>,
    #[serde(rename = "message")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub message: EssPresence<::std::string::String>,
    #[serde(rename = "progress")]
    #[serde(deserialize_with = "ess_required")]
    pub progress: ::serde_json::Value,
    #[serde(rename = "token")]
    #[serde(deserialize_with = "ess_required")]
    pub token: ::std::boxed::Box<McpHttpExchangeRequestId>,
    #[serde(rename = "total")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub total: EssPresence<::serde_json::Value>,
}

// Source: "/$defs/mcp.http_lifecycle.ServerRequestObservation"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpLifecycleServerRequestObservation {
    #[serde(rename = "reply")]
    #[serde(deserialize_with = "ess_required")]
    pub reply: ::std::boxed::Box<McpHttpLifecycleControlObservation>,
    #[serde(rename = "request")]
    #[serde(deserialize_with = "ess_required")]
    pub request: ::std::boxed::Box<McpHttpExchangeWireObservation>,
}

// Source: "/$defs/mcp.http_lifecycle.ShutdownObservation"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpLifecycleShutdownObservation {
    #[serde(rename = "deletion")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub deletion: EssPresence<::std::boxed::Box<McpHttpLifecycleControlObservation>>,
    #[serde(rename = "interrupted")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub interrupted: EssPresence<::std::boxed::Box<McpHttpLifecycleInterruptedRequest>>,
}

// Source: "/$defs/mcp.http_lifecycle.StopCause"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpLifecycleStopCause {
    #[serde(rename = "caller_cancelled")]
    V0,
    #[serde(rename = "deadline_exhausted")]
    V1,
    #[serde(rename = "future_dropped")]
    V2,
    #[serde(rename = "shutdown")]
    V3,
}

// Source: "/$defs/mcp.http_lifecycle.StreamMessage"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
#[serde(untagged)]
pub enum McpHttpLifecycleStreamMessage {
    V0(EssShapecea226422afd802f),
    V1(EssShape2dfd854e27e8c689),
    V2(EssShapeca3b047f4e2a5937),
}
impl<'de> ::serde::Deserialize<'de> for McpHttpLifecycleStreamMessage {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;
        if let Ok(decoded) = ::serde_json::from_value::<EssShapecea226422afd802f>(value.clone()) {
            return Ok(Self::V0(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShape2dfd854e27e8c689>(value.clone()) {
            return Ok(Self::V1(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShapeca3b047f4e2a5937>(value.clone()) {
            return Ok(Self::V2(decoded));
        }
        Err(::serde::de::Error::custom("no structurally decodable union alternative"))
    }
}

// Source: "/$defs/mcp.http_lifecycle.StreamObservation"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpLifecycleStreamObservation {
    #[serde(rename = "messages")]
    #[serde(deserialize_with = "ess_required")]
    pub messages: ::std::vec::Vec<::std::boxed::Box<McpHttpLifecycleStreamMessage>>,
}

// Source: "/$defs/mcp.http_lifecycle.WorkerCleanup"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpLifecycleWorkerCleanup {
    #[serde(rename = "failure")]
    #[serde(default, skip_serializing_if = "EssPresence::is_absent")]
    pub failure: EssPresence<::std::boxed::Box<McpHttpLifecycleWorkerCleanupFailure>>,
    #[serde(rename = "kill")]
    #[serde(deserialize_with = "ess_required")]
    pub kill: ::std::boxed::Box<McpHttpLifecycleWorkerKillObservation>,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "ess_required")]
    pub state: ::std::boxed::Box<McpHttpLifecycleWorkerCleanupState>,
}

// Source: "/$defs/mcp.http_lifecycle.WorkerCleanupFailure"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpLifecycleWorkerCleanupFailure {
    #[serde(rename = "deadline_exhausted")]
    V0,
    #[serde(rename = "wait_failed")]
    V1,
}

// Source: "/$defs/mcp.http_lifecycle.WorkerCleanupState"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpLifecycleWorkerCleanupState {
    #[serde(rename = "no_child")]
    V0,
    #[serde(rename = "reaped")]
    V1,
    #[serde(rename = "retained")]
    V2,
}

// Source: "/$defs/mcp.http_lifecycle.WorkerInterruption"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpLifecycleWorkerInterruption {
    #[serde(rename = "cause")]
    #[serde(deserialize_with = "ess_required")]
    pub cause: ::std::boxed::Box<McpHttpLifecycleStopCause>,
    #[serde(rename = "cleanup")]
    #[serde(deserialize_with = "ess_required")]
    pub cleanup: ::std::boxed::Box<McpHttpLifecycleWorkerCleanup>,
}

// Source: "/$defs/mcp.http_lifecycle.WorkerKillObservation"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpLifecycleWorkerKillObservation {
    #[serde(rename = "failed")]
    V0,
    #[serde(rename = "not_attempted")]
    V1,
    #[serde(rename = "requested")]
    V2,
}

// Source: "/$defs/mcp.http_lifecycle.WorkerRefusal"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpLifecycleWorkerRefusal {
    #[serde(rename = "cleanup")]
    #[serde(deserialize_with = "ess_required")]
    pub cleanup: ::std::boxed::Box<McpHttpLifecycleWorkerCleanup>,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "ess_required")]
    pub reason: ::std::boxed::Box<McpHttpInvocationRefusalReason>,
}

// Source: "/$defs/mcp.http_observations.AbsentPeerData"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpObservationsAbsentPeerData {
    #[serde(rename = "absent")]
    V0,
}

// Source: "/$defs/mcp.http_observations.BoundedWireBytes"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpObservationsBoundedWireBytes {
    #[serde(rename = "bytes")]
    #[serde(deserialize_with = "ess_required")]
    pub bytes: ::std::string::String,
    #[serde(rename = "counts")]
    #[serde(deserialize_with = "ess_required")]
    pub counts: ::std::boxed::Box<McpHttpObservationsRetentionCounts>,
    #[serde(rename = "message_length")]
    #[serde(deserialize_with = "ess_required")]
    pub message_length: ::std::boxed::Box<McpHttpObservationsMessageLength>,
    #[serde(rename = "retention")]
    #[serde(deserialize_with = "ess_required")]
    pub retention: ::std::boxed::Box<McpHttpObservationsRetentionKind>,
}

// Source: "/$defs/mcp.http_observations.MessageLength"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
#[serde(untagged)]
pub enum McpHttpObservationsMessageLength {
    V0(EssShapedf260743e534db96),
    V1(EssShapee01f56b0270720cc),
}
impl<'de> ::serde::Deserialize<'de> for McpHttpObservationsMessageLength {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;
        if let Ok(decoded) = ::serde_json::from_value::<EssShapedf260743e534db96>(value.clone()) {
            return Ok(Self::V0(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShapee01f56b0270720cc>(value.clone()) {
            return Ok(Self::V1(decoded));
        }
        Err(::serde::de::Error::custom("no structurally decodable union alternative"))
    }
}

// Source: "/$defs/mcp.http_observations.OctetCount"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(transparent)]
pub struct McpHttpObservationsOctetCount(pub ::serde_json::Number);

// Source: "/$defs/mcp.http_observations.PeerData"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]
#[serde(untagged)]
pub enum McpHttpObservationsPeerData {
    V0(EssShape57140dd945206401),
    V1(EssShape89ba6ab534731e6f),
}
impl<'de> ::serde::Deserialize<'de> for McpHttpObservationsPeerData {
    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;
        if let Ok(decoded) = ::serde_json::from_value::<EssShape57140dd945206401>(value.clone()) {
            return Ok(Self::V0(decoded));
        }
        if let Ok(decoded) = ::serde_json::from_value::<EssShape89ba6ab534731e6f>(value.clone()) {
            return Ok(Self::V1(decoded));
        }
        Err(::serde::de::Error::custom("no structurally decodable union alternative"))
    }
}

// Source: "/$defs/mcp.http_observations.PeerError"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpObservationsPeerError {
    #[serde(rename = "code")]
    #[serde(deserialize_with = "ess_required")]
    pub code: ::serde_json::Number,
    #[serde(rename = "data")]
    #[serde(deserialize_with = "ess_required")]
    pub data: ::std::boxed::Box<McpHttpObservationsPeerData>,
    #[serde(rename = "message")]
    #[serde(deserialize_with = "ess_required")]
    pub message: ::std::string::String,
}

// Source: "/$defs/mcp.http_observations.ProtocolRevision"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpObservationsProtocolRevision {
    #[serde(rename = "2025-11-25")]
    V0,
    #[serde(rename = "2026-07-28")]
    V1,
}

// Source: "/$defs/mcp.http_observations.RetentionCounts"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct McpHttpObservationsRetentionCounts {
    #[serde(rename = "limit_octets")]
    #[serde(deserialize_with = "ess_required")]
    pub limit_octets: ::std::boxed::Box<McpHttpObservationsOctetCount>,
    #[serde(rename = "retained_octets")]
    #[serde(deserialize_with = "ess_required")]
    pub retained_octets: ::std::boxed::Box<McpHttpObservationsOctetCount>,
}

// Source: "/$defs/mcp.http_observations.RetentionKind"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpObservationsRetentionKind {
    #[serde(rename = "prefix")]
    V0,
    #[serde(rename = "whole_message")]
    V1,
}

// Source: "/$defs/mcp.http_observations.SendObservation"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpObservationsSendObservation {
    #[serde(rename = "not_sent")]
    V0,
    #[serde(rename = "send_observed")]
    V1,
    #[serde(rename = "unknown")]
    V2,
}

// Source: "/$defs/mcp.http_observations.TerminalObservation"
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum McpHttpObservationsTerminalObservation {
    #[serde(rename = "correlated_terminal")]
    V0,
    #[serde(rename = "incomplete")]
    V1,
}

